# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Diffnav < Formula
  desc "Git diff pager based on delta but with a file tree, à la GitHub"
  homepage "https://github.com/dlvhdr/diffnav"
  license "MIT"

  depends_on "git"
  depends_on "git-delta"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dlvhdr/diffnav/releases/download/v0.12.0/diffnav_Darwin_x86_64.tar.gz"
      sha256 "29a45a968e22703668ed0cd1969cf333b96b039b015755cc5312f80d315a78a1"

      define_method(:install) do
        bin.install "diffnav"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dlvhdr/diffnav/releases/download/v0.12.0/diffnav_Darwin_arm64.tar.gz"
      sha256 "2db80564b9e3687fad83769ef52209fadc56702c03614afb8855261a81d1d38a"

      define_method(:install) do
        bin.install "diffnav"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dlvhdr/diffnav/releases/download/v0.12.0/diffnav_Linux_x86_64.tar.gz"
      sha256 "1531569b74863f08dd82379041fbc9c0cf5103893ac5b3ff053453dd048bb807"
      define_method(:install) do
        bin.install "diffnav"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dlvhdr/diffnav/releases/download/v0.12.0/diffnav_Linux_arm64.tar.gz"
      sha256 "5d23e9b5cc8e4d2be0463886d57ac0590c348e24b5611eb54a4bc84685e707c9"
      define_method(:install) do
        bin.install "diffnav"
      end
    end
  end
end
