# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Diffnav < Formula
  desc "Git diff pager based on delta but with a file tree, à la GitHub"
  homepage "https://github.com/dlvhdr/diffnav"
  version "0.8.1"
  license "MIT"

  depends_on "git"
  depends_on "git-delta"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dlvhdr/diffnav/releases/download/v0.8.1/diffnav_Darwin_x86_64.tar.gz"
      sha256 "c353e2c6df7caac85aab91d9b670eee91d0b100a0b9f1d29a8dfd595d341a496"

      def install
        bin.install "diffnav"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dlvhdr/diffnav/releases/download/v0.8.1/diffnav_Darwin_arm64.tar.gz"
      sha256 "f783f9c81875a76b2ac73b7eed939d00291f639d80fb567768cace17f4298a0d"

      def install
        bin.install "diffnav"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dlvhdr/diffnav/releases/download/v0.8.1/diffnav_Linux_x86_64.tar.gz"
      sha256 "0163dac69438ab310f8ead56c04c939041481569cca9c86f61ebb02c46c671b5"
      def install
        bin.install "diffnav"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dlvhdr/diffnav/releases/download/v0.8.1/diffnav_Linux_arm64.tar.gz"
      sha256 "21dad3d7b87ec2f8900269739627d33aad6bc97a2a539a756c210682b5b2219e"
      def install
        bin.install "diffnav"
      end
    end
  end
end
